name: cache_value
description: On-Memory cache support.
version: 0.0.1
homepage: https://github.com/vivitainc/flutter_cache_value

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  semaphore: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
